### ISSUE TITLE
version1.2 - Image does not show up in GIMP window

### ISSUE THREAD

**Issue by kazuhito84455** [lmotta/gimpselectionfeature_plugin#1]
Bug: Sent map image by clicking on `Send image` button under QGIS -> GIMP, but the image does not show up in Gimp.
Version: 1.2
Environment: QGIS 3.4.3 and QGIS 3.4.4, Gimp 2.10.8
OS: Windows10 (64bit)
Others: Current workaround - Removed v1.2 and re-installed previous version 1.1. It works well.

**Comment by lmotta** [comment]
Thanks for your report.

Please, update the plugin and test again.

**Comment by kazuhito84455** [comment]
Yes, the sent image does show up in Gimp now. Thanks so much!
(Version: 1.3)
