### ISSUE TITLE
2019-06-19T14:38:30     CRITICAL    GimpSelectionFeature : Not found diretory 'GIMP' or 'GIMP plug-ins' in 'C:\Users\Hugo'

### ISSUE THREAD

**Issue by hugonbg** [lmotta/gimpselectionfeature_plugin#3]
Instalei sem problema no QGIS 3.4 porém quando clico no "Gimp Selection Feature" é exibido:
2019-06-19T14:38:30     CRITICAL    GimpSelectionFeature : Not found diretory 'GIMP' or 'GIMP plug-ins' in 'C:\Users\Hugo'

A versão do gimp é a GIMP 2.10.12

**Comment by hugonbg** [comment]
Reiniciei o computador e resolveu.

**Comment by WarthogARJ** [comment]
Same issue, re-starting did not work for me.
