### ISSUE TITLE
 Polygon "gimp_selection" is not passed to GIMP

### ISSUE THREAD

**Issue by Ilgiz88** [lmotta/gimpselectionfeature_plugin#8]
Hello. When resubmitting the map to GIMP, the previous selection is not saved in GIMP. A blank selection card is opened again. How can you fix this? Or does it not work on Windows? (google translate =) )
Windows 10
QGIS 3.16
GIMP 2.10.22
Plugin gimp 1.6

![image](https://user-images.githubusercontent.com/73850101/97909279-c7746e00-1d69-11eb-81de-515cff2ec1aa.png)

=>

![image](https://user-images.githubusercontent.com/73850101/97909232-b4619e00-1d69-11eb-8d88-80f02493079e.png)

I tried different versions, but no result.

**Comment by lmotta** [comment]
Hello,

The logic of plugin is:
1) Send image(QGIS -> GIMP)
Select area in Gimp
2) Get Features(GIMP->QGIS)
Transform select area in Feature(polygons)

The selection area in GIMP depend of image, the new image don't have selection area.

You need manager the feature inside QGIS. The GIMP is only for do get select area.
